name: 🐞报告Bug
description: 报告bug
title: "[Bug]: "
body:
- type: checkboxes
  id: check-list
  attributes:
    label: 检查单
    description: 为避免无效问题和冗余问题，请确保你已完成以下所有操作
    options:
      - label: 我已确认网络环境没有问题
        required: true
      - label: 我已确认ip属地为中国大陆
        required: true
- type: textarea
  id: bug-description
  attributes:
    label: Bug描述
    description: 对Bug清晰简明地描述
  validations:
    required: true
- type: input
  id: android-version
  attributes:
    label: 安卓版本
    description: 你手机使用什么版本的安卓系统？
    placeholder: Android 14
  validations:
    required: true
- type: input
  id: wenku8reader-version
  attributes:
    label: 轻小说文库版本
    description: 轻小说文库(com.cyh128.wenku8reader)的版本
    placeholder: v2.3.1
  validations:
    required: true
- type: textarea
  id: additional-information
  attributes:
    label: 附加信息
    description: 如果你的问题需要进一步解释，或者你所遇到的问题不容易重现，请在此处添加更多信息。（直接把图片、视频拖到编辑框即可添加图片或视频）