name: ✨功能请求
description: 请求添加新功能
title: "[Feature]: "
body:
- type: checkboxes
  id: check-list
  attributes:
    label: 检查单
    description: 为避免无效问题和冗余问题，请确保你已完成以下所有操作
    options:
      - label: 我已确认软件内没有此功能
        required: true
      - label: 我已确认当前issue列表没有相似的请求
        required: true
- type: textarea
  id: feature-description
  attributes:
    label: 功能描述
    description: 说明想要的功能
  validations:
    required: true
- type: textarea
  id: alternatives-considered
  attributes:
    label: 描述你考虑过的替代方案
    description: 对你考虑过的所有替代解决方案或功能的简洁明了的描述
  validations:
    required: false
- type: textarea
  id: additional-information
  attributes:
    label: 附加信息
    description: 如果你的问题需要进一步解释，或者想要表达其他内容，请在此处添加更多信息。（直接把图片、视频拖到编辑框即可添加图片或视频）